/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run "yarn generate-schema-types" to regenerate this file.
 */
export type Test1 = number
export type Test2 = number
export type Test3 = boolean

export interface TestPayload {
	test1: Test1
	test2: Test2
	test3?: Test3
}

export enum Actions {
	Test = 'test',
}
